apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: c2VjcmV0UGFzcw== # base64 encoded value of 'secretPass'
  mysql-user: dXNlcg== # base64 encoded value of 'user'
  mysql-password: cGFzcw== # base64 encoded value of 'pass'